apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-scanning
  namespace: {{ .Values.namespace }}
  labels:
    app: sysdigcloud
type: Opaque
stringData:
  scanning.mysql.password: {{ .Values.sysdig.mysql.secure.password }}
