apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-api  
spec:
  template:
    spec:
      containers:
        - name: api        
          resources:
            limits:
              cpu: "8"
              memory: "8Gi"
            requests:
              cpu: "2"
              memory: "2Gi"
