---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-tcp-services
  namespace: {{ .Values.namespace }}
data:
  "6443": {{ .Values.namespace }}/sysdigcloud-collector:6000:::{{ .Values.namespace }}/sysdigcloud-ssl-secret
