---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: redis-sentinel
  labels:
    app: redis-sentinel
spec:
  ports:
  - port: 26379
    name: redis-sentinel
  selector:
    app: redis-sentinel
