---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: redis-primary
  labels:
    app: redis-primary
spec:
  ports:
  - port: 6379
    name: redis-primary
  selector:
    app: redis-primary
