---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: redis-secondary
  labels:
    app: redis-secondary
spec:
  ports:
  - port: 6379
    name: redis-secondary
  selector:
    app: redis-secondary
