---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: sysdigcloud-elasticsearch
  labels:
    affinity: elasticsearch
    app: sysdigcloud
    component: elasticsearch
    role: elasticsearch
spec:
  selector:
    matchLabels:
      affinity: elasticsearch
      app: sysdigcloud
      component: elasticsearch
      role: elasticsearch
  serviceName: sysdigcloud-elasticsearch
  podManagementPolicy: Parallel
  # The number of replicas needs to be passed to the pods by ensuring that the value of ELASTICSEARCH_GOSSIP_NODES_NUM
  # matches the number set here.
  template:
    metadata:
      labels:
        affinity: elasticsearch
        app: sysdigcloud
        component: elasticsearch
        role: elasticsearch
    spec:
      ## Pod anti-affinity rules ensure that elasticsearch pods run on separate hosts.
      ## You may need to disable these if your number of available kubernetes hosts is less than
      ## the replication factor for your statefulset.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: affinity
                operator: In
                values:
                - elasticsearch
            topologyKey: kubernetes.io/hostname
      containers:
        - name: elasticsearch
          image: quay.io/sysdig/elasticsearch:5.6.15.6-alpine
          securityContext:
            privileged: true
          env:
            - name: ELASTICSEARCH_SERVICE
              value: sysdigcloud-elasticsearch
            - name: ELASTICSEARCH_CLUSTER_NAME
              value: sysdigcloud
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.jvm.options
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
