apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysdigcloud-mysql-cluster
spec:
  template:
    spec:
      containers:
        - name: mysql  
          resources:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 1Gi
