apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysdigcloud-mysql-cluster
spec:
  template:
    spec:
      containers:
        - name: mysql  
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 2Gi      
