apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-mysql-router
spec:
  template:
    spec:
      containers:
        - name: mysql  
          resources:
            limits:
              cpu: "500m"
              memory: 500Mi
            requests:
              cpu: "250m"
              memory: 100Mi
