apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-elasticsearch
spec:
  template:
    spec:
      containers:
        - name: elasticsearch 
          resources:
            limits:
              cpu: "8"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 4Gi      
