apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdigcloud-anchore-core 
spec:
  template:
    spec:
      containers:
        - name: anchore-core    
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1Gi
