apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdigcloud-scanning-alertmgr 
spec:
  template:
    spec:
      containers:
        - name: scanning-alertmgr
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
