apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysdigcloud-scanning-api  
spec:
  template:
    spec:
      containers:
        - name: scanning-api        
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1Gi
