apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: sysdigcloud-postgresql
spec:
  template:
    spec:
      containers:
        - name: postgresql  
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 1Gi     
