apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: sysdigcloud-postgresql
spec:
  template:
    spec:
      containers:
        - name: postgresql  
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 2Gi     
