#defines which scripts needs to be run
#generate - performs templating & kustomization
#install - apply's the generated script in k8s environment
scripts: generate, install
#defines applications needed. Monitor installed by default.
#Secure is optional. Remove secure if not.
apps: monitor, secure
#Size of the cluster. Takes [ small | medium | large ]
#This defines CPU & Memory & Disk & Replicas
#Replicas overwritten - for medium , large by advancedconfig replicas
size: medium
#Set k8s namespace for sysdigcloud
namespace: sysdigcloud
#Set Quay.Io secrets
quaypullsecret: <Insert QuaySecret>
sysdig:
  agentCount: 10
  #Set Sysdig license
  license: <Insert SysdigLicense>
  storageclass:
    name: <Insert StorageClassName>
  dnsName: <Insert DNS Name>
  monitorVersion: 1985
  #Advanced settings
  #autogenerate certificate by default - generate to false and provide crt,key to use existing certs
  certificate:
    generate: true
    crt:
    key:
  #replicas settings
  #default replicas are set based on size - small, medium & large
  #below section acts as a override
  cassandraReplicaCount:
  elasticSearchReplicaCount:
  apiReplicaCount:
  collectorReplicaCount:
  workerReplicaCount:
  anchoreCoreReplicaCount:
  anchoreWorkerReplicaCount:
  scanningApiReplicaCount:
  scanningAlertMgrReplicaCount:
