#This represents the schema version of this config, this version follows semver
#and maintains semver guarantees around versioning.
schema_version: 1.0.0
#Size of the cluster. Takes [ small | medium | large ]
#This defines CPU & Memory & Disk & Replicas
#Replicas can be overwritten for medium , large in advanced   config section
size: medium
#Set Quay.Io secrets
quaypullsecret: <change-me>
#supports aws | gke | hostPath | local
storageClassProvisioner: aws
#Sysdig application config
sysdig:
  agentCount: 10
  #Set Sysdig license
  license: <change-me>
  dnsName: <change-me>
