apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-redis
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: redis
    spec:
      {{- if kindIs "map" .Values.nodeaffinityLabel }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeaffinityLabel.key }}
                operator: In
                values:
                - {{ .Values.nodeaffinityLabel.value }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.airgapped_registry_name | default "quay.io" }}/sysdig/redis:{{ .Values.sysdig.redisVersion }}
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: redis.password
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
