apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: {{ .Values.namespace }}
  labels:
    app: sysdigcloud
    role: redis
spec:
  ports:
    - port: 6379
  selector:
    app: sysdigcloud
    role: redis
