#Set k8s namespace for sysdigcloud
namespace: sysdigcloud
#Set Quay.Io secrets
quaypullsecret: <Insert QuaySecret>
sysdig:
  agentCount: 10
  #Set Sysdig license
  license: <Insert SysdigLicense>
  storageclass:
    name: <Insert StorageClassName>
  dnsName: <Insert DNS Name>
  monitorVersion: 1985
  #Advanced settings
  #autogenerate certificate by default - generate to false and provide crt,key to use existing certs
  certificate:
    generate: true
    crt:
    key:
  #replicas settings
  #default replicas are set based on size - small, medium & large
  #below section acts as a override
  cassandraReplicaCount:
  elasticSearchReplicaCount:
  apiReplicaCount:
  collectorReplicaCount:
  workerReplicaCount:
  anchoreCoreReplicaCount:
  anchoreWorkerReplicaCount:
  scanningApiReplicaCount:
  scanningAlertMgrReplicaCount:
