---
apiVersion: v1
kind: Service
metadata:
  name: redis-events-forwarding
  labels:
    app: sysdigcloud
    role: redis-ef
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: sysdigcloud
    role: redis-ef
