apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysdigcloud-postgresql
spec:
{{- if eq .Values.storageClassProvisioner "hostPath" }}
  template:
    spec:
      volumes:
        - name: data
          hostPath:
            type: DirectoryOrCreate
            path: /var/lib/postgresql/data/pgdata
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 60Gi
        storageClassName: {{ .Values.storageClassName }}
{{- end }}
