apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  template:
    spec:
      containers:
        - name: redis-sentinel 
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "100m"
              memory: 100Mi
