apiVersion: v1
kind: Secret
metadata:
  name: sysdigcloud-anchore
  namespace: {{ .Values.namespace }}
  labels:
    app: sysdigcloud
type: Opaque
stringData:
  anchore.admin.password: {{ .Values.sysdig.secure.admin.password }}
  anchore.db.password: {{ .Values.sysdig.secure.db.password }}
