apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-cassandra
spec:
{{- if eq .Values.storageClassProvisioner "hostPath" }}
  template:
    spec:
      volumes:
        - name: data
          hostPath:
            type: DirectoryOrCreate
            path: /var/lib/cassandra
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
        storageClassName: {{ .Values.storageClassName }}
{{- end }}
