---
apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-collector
  namespace: {{ .Values.namespace }}
  labels:
    app: sysdigcloud
    role: collector
spec:
  clusterIP: None
  ports:
    - port: 6000
      name: secure-collector
      targetPort: 6000
  selector:
    app: sysdigcloud
    role: collector
