apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: sysdigcloud-postgresql
spec:
  template:
    spec:
      containers:
        - name: postgresql  
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "500m"
              memory: 500Mi     
