apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysdigcloud-mysql
spec:
  template:
    spec:
      containers:
        - name: mysql  
          resources:
            requests:
              cpu: 500m
              memory: 1Gi     
