apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-collector  
spec:
  template:
    spec:
      containers:
        - name: collector        
          resources:
            limits:
              cpu: "16"
              memory: "16Gi"
            requests:
              cpu: "4"
              memory: "4Gi"
