{{- if ne .Values.storageClassProvisioner "hostPath" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClassName }}
reclaimPolicy: Retain
volumeBindingMode: Immediate
{{- end }}
