apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-api  
spec:
  template:
    spec:
      containers:
        - name: api        
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
