apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../collector-worker
patches:
  - replicas-collector.yaml
  - resources-collector.yaml
  - replicas-worker.yaml
  - resources-worker.yaml
