apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "100m"
              memory: 100Mi
