apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sysdigcloud-redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "400m"
              memory: 400Mi
