apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-secondary
spec:
  template:
    spec:
      containers:
        - name: redis-secondary
          resources:
            limits:
              cpu: "500m"
              memory: 4Gi
            requests:
              cpu: "100m"
              memory: 1Gi
