apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-secondary
spec:
  template:
    spec:
      containers:
        - name: redis-secondary
          resources:
            limits:
              cpu: "1"
              memory: 8Gi
            requests:
              cpu: "200m"
              memory: 2Gi
